# Smart Phone Addiction Data Cleaning

## Introduction
The rapid growth of smartphone usage has significantly transformed modern lifestyles, influencing how individuals communicate, work, and spend their leisure time. While smartphones offer convenience and connectivity, excessive usage has raised concerns regarding digital addiction and its impact on mental well-being, productivity, and daily habits.

This project utilizes a dataset comprising information from approximately 7,500 individuals, capturing detailed smartphone usage patterns and behavioral indicators. The dataset includes key variables such as daily screen time, number of app opens, time spent on social media, sleep duration, productivity levels, and frequency of phone checking. Additionally, demographic attributes like age, gender, and occupation enable a deeper understanding of how different user groups interact with smartphones.

The primary objective of this analysis is to explore patterns, trends, and relationships within the data to better understand smartphone usage behavior and its potential consequences. 

Through this analysis, the purpose is to identify the indicators of smartphone addiction, examine their impact on lifestyle factors such as sleep and productivity, and provide data-driven insights that can contribute to discussions around digital well-being.

### Questions and Hypotheses
1. **Does increased daily screen time affects an individual's productivity and effeciency?**
    - **Hypotheses**: Higher daily screen time is associated with lower productivity levels.


2. **Does spending more time on social media impact sleep duration?**
    - **Hypotheses**: Individuals who spend more time on social media tend to have shorter sleep durations.


3. **Do people spend more time on smartphones during weekends compared to weekdays?**
    - **Hypotheses**: Average screen time is higher on weekends than on weekdays


4. **Is there any relationship between daily screen time and stress_levels?**
    - **Hypotheses**: Often high duration of daily screen time is associated with high stress levels, but it is also possible that if properly used for entertainment it might decrease the stress


5. **Do individuals who spend more time gaming have different sleep durations?**
    - **Hypotheses**: Higher gaming hours are always associated with reduced sleep duration

## Step 1 - Load Data

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('Dataset/smartphone_addiction_analysis.csv')
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [32]:
df.shape

(7500, 16)

In [33]:
# Checking if any columns have null values
df.isnull().sum()

transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            819
addicted_label               0
dtype: int64

In [34]:
# Summary statistics
df.describe()

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label
count,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000,7500.000000
mean,26.568800,7.499912,3.273484,2.014183,3.242420,6.737561,134.257333,97.832400,9.243827,0.707733
std,5.197108,2.609188,1.585342,1.146039,1.600765,1.283605,66.586883,48.423349,2.718281,0.454835
min,18.000000,3.000000,0.500000,0.000000,0.500000,4.500000,20.000000,15.000000,3.580000,0.000000
25%,22.000000,5.220000,1.910000,1.020000,1.850000,5.630000,76.000000,55.000000,6.960000,0.000000
50%,27.000000,7.525000,3.270000,2.040000,3.230000,6.720000,134.000000,98.000000,9.260000,1.000000
75%,31.000000,9.810000,4.630000,2.990000,4.640000,7.840000,191.000000,140.000000,11.540000,1.000000
max,35.000000,12.000000,6.000000,4.000000,6.000000,9.000000,250.000000,180.000000,14.880000,1.000000

In [35]:
# Checking dataset structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           7500 non-null   str
 1   user_id                  7500 non-null   str
 2   age                      7500 non-null   int64
 3   gender                   7500 non-null   str
 4   daily_screen_time_hours  7500 non-null   float64
 5   social_media_hours       7500 non-null   float64
 6   gaming_hours             7500 non-null   float64
 7   work_study_hours         7500 non-null   float64
 8   sleep_hours              7500 non-null   float64
 9   notifications_per_day    7500 non-null   int64
 10  app_opens_per_day        7500 non-null   int64
 11  weekend_screen_time      7500 non-null   float64
 12  stress_level             7500 non-null   str
 13  academic_work_impact     7500 non-null   str
 14  addiction_level          6681 non-null   str
 15  addicted_label           7500 non-null   int64
dtypes: float64(6), int64(4), str(6)
memory usage: 937.6 KB

## Step 2 - Data Cleaning

In [36]:
# Checking Duplicates
df.duplicated().sum()

np.int64(0)

In [37]:
# Converting data types
df['stress_level'] = df['stress_level'].astype('category')

In [38]:
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [39]:
df['gender'].value_counts()

gender
Male      2553
Other     2486
Female    2461
Name: count, dtype: int64

In [40]:
df['stress_level'].value_counts()

stress_level
High      2560
Low       2503
Medium    2437
Name: count, dtype: int64

In [41]:
df['academic_work_impact'].value_counts()

academic_work_impact
No     3753
Yes    3747
Name: count, dtype: int64

In [42]:
df['addiction_level'].value_counts()

addiction_level
Moderate    2874
Severe      2434
Mild        1373
Name: count, dtype: int64

In [43]:
df['addiction_level'].unique()

<StringArray>
[nan, 'Mild', 'Moderate', 'Severe']
Length: 4, dtype: str

In [44]:
df['addiction_level'] = df['addiction_level'].fillna('None')

In [45]:
df['addiction_level'].value_counts()

addiction_level
Moderate    2874
Severe      2434
Mild        1373
None         819
Name: count, dtype: int64

In [46]:
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,None,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,None,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [47]:
# New features

# Total usage for social media and gaming
df['total_usage'] = df['social_media_hours'] + df['gaming_hours']

# Difference in screen usage during weekend and weekdays
df['week_usage_dff'] = df['weekend_screen_time'] - df['daily_screen_time_hours']

df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label,total_usage,week_usage_dff
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,None,0,2.90,0.72
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,None,0,6.05,1.62
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0,5.19,2.62
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1,7.36,1.94
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1,9.34,2.59

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           7500 non-null   str
 1   user_id                  7500 non-null   str
 2   age                      7500 non-null   int64
 3   gender                   7500 non-null   str
 4   daily_screen_time_hours  7500 non-null   float64
 5   social_media_hours       7500 non-null   float64
 6   gaming_hours             7500 non-null   float64
 7   work_study_hours         7500 non-null   float64
 8   sleep_hours              7500 non-null   float64
 9   notifications_per_day    7500 non-null   int64
 10  app_opens_per_day        7500 non-null   int64
 11  weekend_screen_time      7500 non-null   float64
 12  stress_level             7500 non-null   category
 13  academic_work_impact     7500 non-null   str
 14  addiction_level          7500 non-null   str
 15  addicted_label           7500 non-null   int64
 16  total_usage              7500 non-null   float64
 17  week_usage_dff           7500 non-null   float64
dtypes: category(1), float64(8), int64(4), str(5)
memory usage: 1003.7 KB

In [49]:
# Encoding categorical values:
df['addiction_level_encoded'] = df['addiction_level'].map({
    'None': 0,
    'Mild': 1,
    'Moderate': 2,
    'Severe': 3
})

In [50]:
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label,total_usage,week_usage_dff,addiction_level_encoded
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,None,0,2.90,0.72,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,None,0,6.05,1.62,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0,5.19,2.62,1
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1,7.36,1.94,2
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1,9.34,2.59,3

In [51]:
# Checking if daily screen time is > 24 hours
(df['daily_screen_time_hours'] > 24).value_counts()

daily_screen_time_hours
False    7500
Name: count, dtype: int64

In [52]:
# Checking if sleep hours > 24
(df['sleep_hours'] > 24).value_counts()

sleep_hours
False    7500
Name: count, dtype: int64

In [53]:
# Checking if sleep hours < 0
(df['sleep_hours'] <= 0).value_counts()

sleep_hours
False    7500
Name: count, dtype: int64

In [54]:
# Checking unique values in transaction id and user id
df['transaction_id'].unique()

<StringArray>
['TXN00001', 'TXN00002', 'TXN00003', 'TXN00004', 'TXN00005', 'TXN00006',
 'TXN00007', 'TXN00008', 'TXN00009', 'TXN00010',
 ...
 'TXN07491', 'TXN07492', 'TXN07493', 'TXN07494', 'TXN07495', 'TXN07496',
 'TXN07497', 'TXN07498', 'TXN07499', 'TXN07500']
Length: 7500, dtype: str

In [55]:
df['user_id'].unique()

<StringArray>
['U00001', 'U00002', 'U00003', 'U00004', 'U00005', 'U00006', 'U00007',
 'U00008', 'U00009', 'U00010',
 ...
 'U07491', 'U07492', 'U07493', 'U07494', 'U07495', 'U07496', 'U07497',
 'U07498', 'U07499', 'U07500']
Length: 7500, dtype: str

In [56]:
# Deleting transaction_id as User_id serves unique values
df.drop('transaction_id', axis='columns', inplace = True)

In [57]:
df.head()

,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label,total_usage,week_usage_dff,addiction_level_encoded
0,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,None,0,2.90,0.72,0
1,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,None,0,6.05,1.62,0
2,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0,5.19,2.62,1
3,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1,7.36,1.94,2
4,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1,9.34,2.59,3

In [58]:
df.to_csv('Dataset/cleaned_data.csv', index=False)